%%{ init: { "theme": "default" } }%%
graph TD

  %% 📘 Normalized domain
  NormalizedRestTickerSnapshot["<b>NormalizedRestTickerSnapshot</b>
  ordinal_sort_position
  timestamp__nz_tick
  ticker_name__nz_tick
  ticker_symbol__nz_tick
  change_pct__nz_tick
  price__nz_tick?
  volume__nz_tick?
  currnt_day_stats_high?
  current_day_stats_low?"]:::normalized

SortedNormalizedTickerSnapshot["<b>SortedNormalizedTickerSnapshot</b>
  ordinal_sort_position
  (extends NormalizedRestTickerSnapshot)"]:::normalized

  EodhdWebSocketSnapshot["<b>EodhdWebSocketSnapshot</b>
  s
  ap
  as
  bp
  bs
  t"]:::eodhd

  %% 📗 Leaderboard domain
  LeaderboardRestTickerSnapshot["<b>LeaderboardRestTickerSnapshot</b>
  ticker_name__ld_tick
  pct_change__ld_tick
  timestamp__ld_tick
  volume__ld_tick
  pct_change_velocity__ld_tick
  pct_change_acceleration__ld_tick
  volume_velocity__ld_tick
  volume_acceleration__ld_tick
  ordinal_sort_position
  leaderboard_momentum_score
  leaderboard_rank
  num_consecutive_appearances"]:::leaderboard

  LeaderboardTickerTransformer["<b>LeaderboardTickerTransformer</b>
  transform(input: NormalizedRestTickerSnapshot): LeaderboardRestTickerSnapshot"]:::leaderboard

  %% 🟠 Polygon domain
  FlatRawPolygonTickerSnapshot["<b>FlatRawPolygonTickerSnapshot</b>
  polygon_ticker_name
  priceChangeTodayAbs
  priceChangeTodayPerc
  lastTradeTimestampNs
  tradingVolumeToday
  rawTickerSnapshot
  currDay
  prevDay
  minute
  lastQuote
  lastTrade"]:::polygon

  PolygonSnapshotTransformer["<b>PolygonSnapshotTransformer</b>
  transform(input: FlatRawPolygonTickerSnapshot): NormalizedRestTickerSnapshot"]:::polygon

  %% 🟣 Raw / Transformer
  RawRestApiTckerSnapshotTransformer["<b>RawRestApiTckerSnapshotTransformer</b>"]:::raw
  DefaultTickerSnapshotTransformer["<b>DefaultTickerSnapshotTransformer</b>
  transform(TIn, position: number): TOut"]:::raw

  %% 🔀 Updated Relationship Annotations
  FlatRawPolygonTickerSnapshot -- "transforms to" --> NormalizedRestTickerSnapshot
  EodhdWebSocketSnapshot -- "transforms to" --> NormalizedRestTickerSnapshot
  SortedNormalizedTickerSnapshot -- "derives from" --> NormalizedRestTickerSnapshot
  NormalizedRestTickerSnapshot -- "composed in" --> LeaderboardRestTickerSnapshot
  LeaderboardRestTickerSnapshot -- "transforms to" --> SortedNormalizedTickerSnapshot
  DefaultTickerSnapshotTransformer -- "implemented →" --> PolygonSnapshotTransformer
  DefaultTickerSnapshotTransformer -- "implemented by →" --> LeaderboardTickerTransformer
  RawRestApiTckerSnapshotTransformer -- "data input" --> FlatRawPolygonTickerSnapshot

  %% Styles
  classDef normalized fill:light-grey,stroke:#004085,stroke-width:4
  classDef leaderboard fill:#c9ffff,stroke:#155724;
  classDef polygon fill:#ffeeba,stroke:#856404;
  classDef raw fill:#fff,stroke:#5c2a91, stroke-width:3;
  classDef eodhd fill:#fff,stroke:#5c2a91;
